name: edca-lab
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - pip:
    - fairlearn==0.12.0
    - flaml==2.3.6
    - lightgbm==4.6.0
    - openml==0.15.1
    - seaborn==0.13.2
    - setuptools==78.1.1
    - torchvision==0.23.0
    - tpot==0.12.2
    - wheel==0.45.1
    - matplotlib==3.10.6
    - optuna==3.4.0
    - optunahub==0.4.0
    - xgboost==3.0.5